spring:
  #  datasource:
  #    driverClassName: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://192.168.207.128:3306/catalystplus?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
  #    username: root
  #    password: 123456

  redis:
    host: redis-headless
    password:
    port: 6379
    timeout: 15000
    jedis:
      pool:
        max-active: 600
        max-idle: 300
        max-wait: 15000
        min-idle: 10

rocketmq:
  ###连接地址nameServer
  #name-server: 127.0.0.1:9876
  name-server: 116.62.104.15:6789
  producer:
    group: admin-producer
